ALTER TABLE skills DROP CONSTRAINT skills_skill_type_check;

UPDATE skills SET skill_type = CASE skill_type
  WHEN 'LANGUAGE' THEN 'PROGRAMMING_LANGUAGE'
  WHEN 'FRAMEWORK_LIBRARY' THEN 'FRAMEWORK'
  WHEN 'TOOL_PLATFORM' THEN 'TOOL'
  WHEN 'DOMAIN' THEN 'TECHNICAL_DOMAIN'
  WHEN 'PRACTICE' THEN 'ENGINEERING_PRACTICE'
  WHEN 'SOFT_SKILL' THEN 'ENGINEERING_PRACTICE'
  ELSE 'ENGINEERING_PRACTICE'
END;

ALTER TABLE skills ADD CONSTRAINT skills_skill_type_check CHECK(skill_type IN (
  'PROGRAMMING_LANGUAGE','FRAMEWORK','LIBRARY','TOOL','PLATFORM','DATABASE','CLOUD',
  'OPERATING_SYSTEM','PROTOCOL_API','HARDWARE','TECHNICAL_DOMAIN','ENGINEERING_PRACTICE'
));

CREATE TABLE job_role_tags (
  job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  role_tag text NOT NULL CHECK(role_tag IN (
    'GENERAL_SWE','FRONTEND','BACKEND','FULL_STACK','MOBILE','DESKTOP','EMBEDDED','FIRMWARE',
    'SYSTEMS','INFRASTRUCTURE','PLATFORM','CLOUD','DEVOPS','SRE','DATA_ENGINEERING','DATA_SCIENCE',
    'MACHINE_LEARNING','AI_AGENT','AI_INFRASTRUCTURE','MLOPS','GRAPHICS','GAMING','ROBOTICS',
    'SECURITY','NETWORKING','DATABASE','COMPILERS','DEVELOPER_TOOLS','QA_TESTING','AUTOMATION'
  )),
  display_order integer NOT NULL CHECK(display_order BETWEEN 0 AND 1),
  PRIMARY KEY(job_id, role_tag),
  UNIQUE(job_id, display_order)
);

CREATE INDEX job_role_tags_role_idx ON job_role_tags(role_tag, job_id);
